name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # It just does git clone but for the repo that you are currently using
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      - name: ping google
        run:  curl -I https://google.com
      - name: ls -la check
        run:  ls -la
      - name: Make script executable
        run: chmod +x ./show_time_israel.sh
      - name: show data and time
        run: ./show_time_israel.sh
      - name: show ployndrom number
        run: python3 ./polyndrom.py

      - name: create folder and file
        run: |
          mkdir -p test-folder
          echo "Hello from inside a file!" > test-folder/file.txt
          echo "Contents of test-folder:"
          ls -la test-folder
      - name: print hello world
        run: echo “Hello World”
      - name: docker v
        run: docker -v



