name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - show files
        run: |
          pwd
          ls -al

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
