name: Docker Build & Push

on:
  push:
    branches:
      - main  # Only run when pushing to main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Debug to confirm where we are
      - name: Debug - show current directory and files
        run: |
          echo "PWD is:"
          pwd
          echo "Files are:"
          ls -R

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build and push Docker image
      - name: Build and Push
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest --push .
